# Numpy

In [33]:
import numpy as np

In [4]:
Array = np.array([1,-45,23,67,98,20])
print(Array)

[  1 -45  23  67  98  20]


In [5]:
Array2 = np.array([[23,19,6],[56,78,90],[30,69,49]])
print(Array2)

[[23 19  6]
 [56 78 90]
 [30 69 49]]


In [23]:
Array3 = np.array([[[20,40,60],[11,22,33],[10,30,50]]])
print(Array3)

[[[20 40 60]
  [11 22 33]
  [10 30 50]]]


# Shape

In [24]:
print(Array.shape)

(6,)


In [25]:
print(Array2.shape)

(3, 3)


In [9]:
print(Array3.shape)

(1, 3, 3)


# ndim

In [10]:
print(Array2.ndim)

2


In [11]:
print(Array.ndim)

1


In [12]:
print(Array3.ndim)

3


# Size

In [13]:
print(Array.size)

6


In [14]:
print(Array2.size)

9


In [15]:
print(Array3.size)

9


In [16]:
print(Array[3])

67


# Slicing of Array

In [31]:
print(Array2)
print(Array2[2:3])

[[23 19  6]
 [56 78 90]
 [30 69 49]]
[[30 69 49]]


# To update the exiting array

In [18]:
Array[1]=20
print(Array)

[ 1 20 23 67 98 20]


In [19]:
Array[0]=30
print(Array)

[30 20 23 67 98 20]


# accessing single element in multi dim

In [20]:
print(Array3[0,1,2])

33


In [21]:
print(Array2[1:3])# slicing of two dim

[[56 78 90]
 [30 69 49]]


In [27]:
print(Array2[:,:2])

[[23 19]
 [56 78]
 [30 69]]


In [28]:
print(Array2)

[[23 19  6]
 [56 78 90]
 [30 69 49]]


In [22]:
Array2 = np.array([[23,19,6],[56,78,90],[30,69,49]])
print(Array2)

[[23 19  6]
 [56 78 90]
 [30 69 49]]


In [35]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [36]:
print(array[:,:])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [39]:
print(array[:2,0:2])

[[[1 2 3]
  [4 5 6]]]
