# Linear algebra  with machine learing

#### vectors and dot products

In [2]:
import numpy as np

In [7]:
# vectors and dot product
array1 = np.array([1,2,3])
array2 =np.array([4,5,6])
print(np.dot(array1,array2))

32


#### matrices and operations (2D)


In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [22]:
c = np.array([[1,2,3],[0,1,4],[5,6,0]])
d = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(c)
print(d)

[[1 2 3]
 [0 1 4]
 [5 6 0]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


#### Addition and sub of matrix (2D)

In [23]:
print("a+b\n",a+b)
print("a-b\n",a-b)

a+b
 [[ 6  8]
 [10 12]]
a-b
 [[-4 -4]
 [-4 -4]]


#### Addition and sub of matrix (3D)

In [24]:
print("c+d\n",c+d)
print("c-d\n",c-d)

c+d
 [[11 13 15]
 [13 15 19]
 [21 23 18]]
c-d
 [[ -9  -9  -9]
 [-13 -13 -11]
 [-11 -11 -18]]
