# Linear algebra  with machine learing

#### vectors and dot products

In [20]:
import numpy as np

In [21]:
# vectors and dot product
array1 = np.array([1,2,3])
array2 =np.array([4,5,6])
print(np.dot(array1,array2))

32


#### matrices and operations (2D)


In [22]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [23]:
c = np.array([[1,2,3],[0,1,4],[5,6,0]])
d = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(c)
print(d)

[[1 2 3]
 [0 1 4]
 [5 6 0]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


#### Addition and sub of matrix (2D)

In [24]:
print("a+b\n",a+b)
print("a-b\n",a-b)

a+b
 [[ 6  8]
 [10 12]]
a-b
 [[-4 -4]
 [-4 -4]]


#### Addition and sub of matrix (3D)

In [25]:
print("c+d\n",c+d)
print("c-d\n",c-d)

c+d
 [[11 13 15]
 [13 15 19]
 [21 23 18]]
c-d
 [[ -9  -9  -9]
 [-13 -13 -11]
 [-11 -11 -18]]


# matrix element wise multi

In [26]:
print(a*b)

[[ 5 12]
 [21 32]]


In [27]:
print(c*d)

[[ 10  22  36]
 [  0  14  60]
 [ 80 102   0]]


# dot product of 2D array

In [28]:
print(a@b)

[[19 22]
 [43 50]]


In [29]:
print(a,b)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [30]:
print(c@d)

[[ 84  90  96]
 [ 77  82  87]
 [128 139 150]]


# transpose of matrix

In [31]:
print(a.T)

[[1 3]
 [2 4]]


In [32]:
print(c.T)

[[1 0 5]
 [2 1 6]
 [3 4 0]]


# identity of matrix

In [33]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
y = np.array([[[1,4,5],[3,4,5],[6,7,8]]])
print(x)
print(y)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 4 5]
  [3 4 5]
  [6 7 8]]]


In [36]:
print("x+y\n",x+y)
print("x-y\n",x-y)

x+y
 [[[ 2  6  8]
  [ 7  9 11]
  [13 15 17]]]
x-y
 [[[ 0 -2 -2]
  [ 1  1  1]
  [ 1  1  1]]]


In [37]:
print("x*y\n",x*y)

x*y
 [[[ 1  8 15]
  [12 20 30]
  [42 56 72]]]


In [38]:
print(x@y)

[[[ 25  33  39]
  [ 55  78  93]
  [ 85 123 147]]]


In [39]:
print(x.shape)
print(y.shape)

(1, 3, 3)
(1, 3, 3)


In [40]:
print(x.T)

[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]

 [[3]
  [6]
  [9]]]


# inverse of  matrix

In [42]:
a_inv = np.linalg.inv(a)
print(a_inv)
print(a)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 2]
 [3 4]]


In [43]:
b_inv = np.linalg.inv(b)
print(b_inv)
print(b)

[[-4.   3. ]
 [ 3.5 -2.5]]
[[5 6]
 [7 8]]


# verify a*a-1=eye(I) identity

In [44]:
print(np.round(a@a_inv))

[[1. 0.]
 [0. 1.]]


In [46]:
# determiant of matrix

In [47]:
det_a = np.linalg.det(a)
print(det_a)

-2.0000000000000004


In [49]:
det_x = np.linalg.det(x)
print(det_x)
print(x)

[0.]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# eigen values and eigen vectors

In [51]:
print(a)
eig_vals,eig_vecs = np.linalg.eig(a)
print("e_values",eig_vals)
print("e_vectors",eig_vecs)


[[1 2]
 [3 4]]
e_values [-0.37228132  5.37228132]
e_vectors [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [52]:
# Iris Flower