In [2]:
import numpy as np
import pandas as pd

#  NumPy

### 1. Create a NumPy array with numbers from 1 to 15 and reshape it into a 3x5 matrix. Print the shape and dimensions of the array.

In [24]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Array = ",array)
print("Re-shape  = ",array.reshape(3,5).shape)
print("Shape = ",array.shape)
print("Dimensions = ",array.reshape(3,5).ndim)

Array =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Re-shape  =  (3, 5)
Shape =  (15,)
Dimensions =  2


### 2. Generate a 4x4 array with random integers from 10 to 99. Find and print the maximum value of each row.

In [4]:
array2 = np.array([[11,22,55,80],[72,23,45,10],[25,34,12,14],[14,18,69,67]])
print(array2)

[[11 22 55 80]
 [72 23 45 10]
 [25 34 12 14]
 [14 18 69 67]]


In [5]:
print(array2[0].max())
print(array2[1].max())
print(array2[2].max())
print(array2[3].max())

80
72
34
69


### 3. Create two 2x2 arrays and perform both element-wise multiplication and matrix multiplication.


In [6]:
array3 = np.array([[10,12],[3,2]])
array4 = np.array([[5,5],[6,10]])
print(array3*array4)#element wise multi

[[50 60]
 [18 20]]


In [7]:
#dot matrix
print(array3@array4)

[[122 170]
 [ 27  35]]


#  Pandas 

### 4. Create a DataFrame with columns: Name, Age, and City for 4 people. Display the first two rows.


In [8]:
info = {
    'Name': ['Vaibhavi', 'Vaishnavi', 'komal', 'pooja'],
    'Age': [25, 30, 22, 28],
    'City': ['Pune', 'Mumbai', 'Delhi', 'solapur']
}
df = pd.DataFrame(info)
print( df.head(2))

        Name  Age    City
0   Vaibhavi   25    Pune
1  Vaishnavi   30  Mumbai


### 5. Filter the DataFrame to show only people whose age is greater than 25.

In [9]:
Age = df[df['Age']>=25]
print(Age)

        Name  Age     City
0   Vaibhavi   25     Pune
1  Vaishnavi   30   Mumbai
3      pooja   28  solapur


### 6. Add a new column called Salary to the DataFrame and then sort it in descending order based on salary.


In [10]:
df['Salary'] = [50000, 60000, 45000, 70000]
sort = df.sort_values(by='Salary',inplace = True,ascending=False)
print(sort)
print(df)

None
        Name  Age     City  Salary
3      pooja   28  solapur   70000
1  Vaishnavi   30   Mumbai   60000
0   Vaibhavi   25     Pune   50000
2      komal   22    Delhi   45000


#  Python Functions


### 7. Write a function that takes a number and returns True if it is even, otherwise False.


In [11]:
def Check_even(i):
        if i%2==0:
            print("True")
        else:
            print("False")
Check_even(2)

True


### 8. Write a function that takes a list of numbers and returns the sum of all numbers.


In [12]:
def numbers(list):
    total = sum(list)
    print(total)
numbers([1,2,3,4])

10


### 9. Write a function that takes a string and returns it reversed (without using slicing)

In [13]:
def reverse_string_for_loop(s):
    reversed_s = ""
    for char in s:
        reversed_s = char + reversed_s  # Prepend each character
    return reversed_s

# Example usage
print(reverse_string_for_loop("Hello"))  # Output: olleh

olleH


# Write a function that takes a list of numbers and returns the greatest of all numbers.


In [14]:
def numbers(list):
    total = max(list)
    print(total)
numbers([1,2,3,4])

4


In [15]:
def number(list):
    greatest = list[0]
    for i in list:
        if i >= greatest:
            greatest = i
    print(greatest)

number([2,4,7,9,12])
        

12


In [16]:
listtt = [2,4,7,9,12]
for i in listtt:
    print(i)

2
4
7
9
12


### Create a DataFrame with columns: Name, Age, Department, Salary, City.

### Filter employees who:

### Are older than 30

### Earn more than ₹60,000

### Work in either "Engineering" or "Design"

### Live in cities starting with "M" or "D"

In [17]:
info = {
    'Name': ['Vaibhavi', 'Vaishnavi', 'komal', 'pooja'],
    'Age': [45, 30, 22, 28],
    'Dept':['Artist','Designer','model','Engineering'],
    'City': ['Pune', 'Mumbai', 'Delhi', 'solapur'],
    'Salary':[80000,30000,45000,75000]
}
df = pd.DataFrame(info)
print(df)

        Name  Age         Dept     City  Salary
0   Vaibhavi   45       Artist     Pune   80000
1  Vaishnavi   30     Designer   Mumbai   30000
2      komal   22        model    Delhi   45000
3      pooja   28  Engineering  solapur   75000


In [18]:
Age = df[df['Age']>=30]
print(Age)

        Name  Age      Dept    City  Salary
0   Vaibhavi   45    Artist    Pune   80000
1  Vaishnavi   30  Designer  Mumbai   30000


In [19]:
Salary = df[df['Salary']>60000]
print(Salary)

       Name  Age         Dept     City  Salary
0  Vaibhavi   45       Artist     Pune   80000
3     pooja   28  Engineering  solapur   75000


In [20]:
dept_check = df[df['Dept'].isin(['Engineering', 'Designer'])]

print(dept_check)

        Name  Age         Dept     City  Salary
1  Vaishnavi   30     Designer   Mumbai   30000
3      pooja   28  Engineering  solapur   75000


In [21]:
city_check = df[df['City'].str.startswith(('M', 'D'))]
print(city_check)


        Name  Age      Dept    City  Salary
1  Vaishnavi   30  Designer  Mumbai   30000
2      komal   22     model   Delhi   45000


In [22]:
list = ['Vaibhavi','Adil','Advaith','vaishnavi']
for items in list:
    if items.startswith('A'):
        print(items)

Adil
Advaith


In [23]:
def numbers(list):
    max=list[0]
    min=list[0]
    for i in list:
        if i>=max:
            max=i
        else:
            min=i
    print(max,min)
numbers([19,27,45,2])

45 2
