# Home Work1

In [4]:
import numpy as np
import pandas as pd

In [5]:
#1. Create a 1D NumPy array of 10 numbers from 1 to 10
Array = np.array([10,20,30,40,50,60,70])
print(Array)

[10 20 30 40 50 60 70]


In [6]:
#2. Create a 2D NumPy array with shape (3,3) filled with numbers from 1 to 9
array2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#3.Create an array of 5 zeros and another of 5 ones
 

In [8]:
#4. Create an array of even numbers between 10 and 30


In [9]:
#5. Add, subtract, multiply, and divide two NumPy arrays of the same shape

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Add:", a + b)
print("Subtract:", a - b)
print("Multiply:", a * b)
print("Divide:", a / b)

Add: [11 22 33]
Subtract: [ 9 18 27]
Multiply: [10 40 90]
Divide: [10. 10. 10.]


In [10]:
#6. Find the mean, sum, min, and max of a NumPy array

arr = np.array([4, 7, 1, 9, 3])

print("Mean:", arr.mean())
print("Sum:", arr.sum())
print("Min:", arr.min())
print("Max:", arr.max())


Mean: 4.8
Sum: 24
Min: 1
Max: 9


In [11]:
#7. Reshape a 1D array of 12 elements into a 3x4 2D array

In [12]:
# 8. Slice an array to get the first 3 elements
arr4 = np.array([5, 10, 15, 20, 25])
print(arr4[:3])

[ 5 10 15]


In [13]:
#9. Generate a random integer array of size (2,3) between 0 and 50



In [14]:
#1. Create a Pandas Series from a list: [10, 20, 30, 40, 50]
array = [10,20,40,50]
series = pd.Series(array)
print(series)

0    10
1    20
2    40
3    50
dtype: int64


In [ ]:
#2. Create a Series with custom index: ['a', 'b', 'c', 'd', 'e']
custom_series = pd.Series(array,index = ['a','b','c','d'])
print(custom_series)

In [ ]:
#3. Access the 3rd element from the Series
print(series[2])


In [ ]:
# 4. Perform basic operations like +10, 2 on the Series


In [ ]:
#5. Create a DataFrame with 3 columns: Name, Age, City using a dictionary

data = {
    'Name': ['vaibhavi', 'Rakshita', 'Mrinal'],
    'Age': [19, 20, 25],
    'City': ['Pune', 'Solapur', 'Mumbai']
}

data_frame = pd.DataFrame(data)
print(data_frame)

In [ ]:
#6. Display first 3 rows using head() and last 2 rows using tail()
data_frame.head(3)

In [ ]:
data_frame.tail(2)

In [ ]:
#7. Use describe() to get summary statistics of a DataFrame with numeric values


In [ ]:
#8. Add a new column Gender to the existing DataFrame


In [ ]:
#9. Filter rows where Age > 25


In [ ]:
#10. Sort the DataFrame by Age column in descending order

# Home work 2

In [15]:
#1. Try to implement continue statement in for loops as well as while loop
for i in range (1,11):
    if i%2!=0:
        continue
    print(i)

2
4
6
8
10


In [16]:
# while loop
i = 1
while i <= 10:
    i += 1
    if i%2== 0:
        continue
    print(i)


3
5
7
9
11


In [17]:
# 2. Print even numbers from 1 to 50 using range and for loop
for i in range(1, 51):
    if i % 2 == 0:
        print(i)


2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [18]:
#3 Take a number (e.g. 80) and print all odd numbers till that number using while loop
i = 1
while i <= 80:
    if i % 2 != 0:
        print(i)
    i += 1


1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
